# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "523da2e01991849fcb6e6b22b826ae22"
name = "Date-picker-App"
handle = "date-picker-app"
application_url = "https://shopify.dev/apps/default-app-home-discount"
embedded = true

[build]
dev_store_url = "test-checkout-extensiblity.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, unauthenticated_read_product_tags"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
